name: CI - Emmy

on:
  workflow_dispatch:

jobs:
  run:
    uses: ./.github/workflows/emulator-runner.yml
    with:
      emulator: Emmy
      needs_chromedriver: true
      needs_audio: false
      extra_requirements: requirements-emmy.txt
