name: CI - VisualBoyAdvance-M

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    uses: ./.github/workflows/emulator-runner.yml
    with:
      emulator: VisualBoyAdvance-M
      needs_audio: true

  deploy-pages:
    needs: run
    uses: ./.github/workflows/deploy-pages.yml
