name: Emulator Runner

on:
  workflow_call:
    inputs:
      emulator:
        required: true
        type: string
      needs_chromedriver:
        required: false
        type: boolean
        default: false
      needs_audio:
        required: false
        type: boolean
        default: true
      extra_requirements:
        required: false
        type: string
        default: ''

jobs:
  run-emulator:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - name: Install base Python requirements
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements-core.txt

      - name: Install extra Python requirements
        if: ${{ inputs.extra_requirements != '' }}
        run: python -m pip install -r ${{ inputs.extra_requirements }}

      - name: Install ChromeDriver
        if: ${{ inputs.needs_chromedriver }}
        uses: nanasess/setup-chromedriver@v2.3.0

      - name: Install Scream
        if: ${{ inputs.needs_audio }}
        shell: powershell
        run: |
          Start-Service audio*
          Invoke-WebRequest https://github.com/duncanthrax/scream/releases/download/3.6/Scream3.6.zip -OutFile C:\Scream3.6.zip
          Extract-7Zip -Path C:\Scream3.6.zip -DestinationPath C:\Scream
          $cert = (Get-AuthenticodeSignature C:\Scream\Install\driver\Scream.sys).SignerCertificate
          $store = [System.Security.Cryptography.X509Certificates.X509Store]::new("TrustedPublisher", "LocalMachine")
          $store.Open("ReadWrite")
          $store.Add($cert)
          $store.Close()
          cd C:\Scream\Install\driver
          C:\Scream\Install\helpers\devcon install Scream.inf *Scream

      - name: Run emulator tests
        run: python main.py --emulator "${{ inputs.emulator }}"

      - name: Upload emulator results
        uses: actions/upload-artifact@v7
        with:
          name: ${{ inputs.emulator }}-results
          path: '*.json'
          if-no-files-found: ignore
